version: "3.7"
services:
  nomad:
    image: nomad-runtime:latest
    container_name: nomad
    cap_add:
      - SYS_ADMIN
    command:
      - "/nomad/bin/nomad"
      - "agent"
      - "-dev"
      - "-config=/nomad/config/server.conf"
    restart: unless-stopped
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
      - ${CONFIG_SVC_PORT}:${CONFIG_SVC_PORT}
    environment:
      - CONFIG_SVC=${CONFIG_SVC}
      - NOMAD_ENDPOINT=${NOMAD_ENDPOINT}
      - TRACE_ENDPOINT=${TRACE_ENDPOINT}
      - METER_ENDPOINT=${METER_ENDPOINT}

  nomad-init:
    image: nomad-runtime:latest
    container_name: nomad-init
    command:
      - "/nomad/bootstrap/bootstrap-nomad-dev-jobs.sh"
    restart: "no"
    environment:
      - CONFIG_SVC=${CONFIG_SVC}
      - NOMAD_ENDPOINT=${NOMAD_ENDPOINT}
      - TRACE_ENDPOINT=${TRACE_ENDPOINT}
      - METER_ENDPOINT=${METER_ENDPOINT}
    depends_on:
      - nomad
